# -*- coding: utf-8 -*-
"""lab-jupyter-launch-site-location-v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s44t8Ywc0jo11gQ6RO4Ie79bnWN89MTq

<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Launch Sites Locations Analysis with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:
- **TASK 1:** Mark all launch sites on a map
- **TASK 2:** Mark the success/failed launches for each site on the map
- **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:
"""

!pip3 install folium
!pip3 install wget
!pip3 install pandas

import folium
import wget
import pandas as pd

# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

"""If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/DV0101EN-3-5-1-Generating-Maps-in-Python-py-v2.0.ipynb)

## Task 1: Mark all launch sites on a map

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.
"""

# Download and read the `spacex_launch_geo.csv`
spacex_csv_file = wget.download('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv')
spacex_df=pd.read_csv(spacex_csv_file)

"""Now, you can take a look at what are the coordinates for each site.

"""

# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

"""Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.
"""

# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

"""We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example,

"""

# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

"""and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

_TODO:_  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`
"""

# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label

"""The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:
- Are all launch sites in proximity to the Equator line?
- Are all launch sites in very close proximity to the coast?

Also please try to explain your findings.

# Task 2: Mark the success/failed launches for each site on the map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not
"""

spacex_df.tail(10)

"""Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object
"""

marker_cluster = MarkerCluster()

"""_TODO:_ Create a new column in `launch_sites` dataframe called `marker_color` to store the marker colors based on the `class` value

"""

# Calcular la ubicación promedio para centrar el mapa
avg_lat = spacex_df['Lat'].mean()
avg_lon = spacex_df['Long'].mean()

# Crear el mapa base
launch_map = folium.Map(location=[avg_lat, avg_lon], zoom_start=4)

# Definir la función para obtener el color del marcador
def get_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'

# Iterar sobre cada lanzamiento en el DataFrame
for index, row in spacex_df.iterrows():
    # Obtener la latitud y longitud del sitio de lanzamiento
    site_lat = row['Lat']
    site_lon = row['Long']
    launch_site_name = row['Launch Site']
    launch_outcome = row['class']

    # Obtener el color del marcador usando la función
    marker_color = get_marker_color(launch_outcome)

    # Crear un marcador para el lanzamiento
    folium.CircleMarker(
        [site_lat, site_lon],
        radius=5,
        color=marker_color,
        fill=True,
        fill_color=marker_color,
        fill_opacity=0.7,
        tooltip=f"Sitio: {launch_site_name}, Éxito: {launch_outcome}"
    ).add_to(launch_map)

# Mostrar el mapa
launch_map

# Function to assign color to launch outcome
def assign_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'

spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)
spacex_df.tail(10)

"""_TODO:_ For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

"""

# Calcular la ubicación promedio para centrar el mapa
avg_lat = spacex_df['Lat'].mean()
avg_lon = spacex_df['Long'].mean()

# Crear el mapa base
site_map = folium.Map(location=[avg_lat, avg_lon], zoom_start=4)

# Crear un MarkerCluster
marker_cluster = MarkerCluster().add_to(site_map)

# Función para obtener el color del marcador
def get_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'

# Iterar sobre cada lanzamiento en el DataFrame
for index, row in spacex_df.iterrows():
    # Obtener la latitud y longitud del sitio de lanzamiento
    site_lat = row['Lat']
    site_lon = row['Long']
    launch_site_name = row['Launch Site']
    launch_outcome = row['class']

    # Obtener el color del marcador usando la función
    marker_color = get_marker_color(launch_outcome)

    # Crear un marcador para el lanzamiento y añadirlo al MarkerCluster
    marker = folium.Marker(
        location=[site_lat, site_lon],
        icon=folium.Icon(color='white', icon_color=marker_color),
        tooltip=f"Sitio: {launch_site_name}, Éxito: {launch_outcome}"
    )
    marker_cluster.add_child(marker)

# Mostrar el mapa
site_map

"""Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

# TASK 3: Calculate the distances between a launch site to its proximities

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)
"""

# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

"""Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

You can calculate the distance between two points on the map based on their `Lat` and `Long` values using the following method:
"""

from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

"""_TODO:_ Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

"""

def calculate_distance(lat1, lon1, lat2, lon2):
    """
    Calcula la distancia entre dos puntos en la Tierra utilizando la fórmula haversine.

    Args:
        lat1 (float): Latitud del primer punto.
        lon1 (float): Longitud del primer punto.
        lat2 (float): Latitud del segundo punto.
        lon2 (float): Longitud del segundo punto.

    Returns:
        float: Distancia en kilómetros entre los dos puntos.
    """
    R = 6371  # Radio de la Tierra en kilómetros

    lat1 = math.radians(lat1)
    lon1 = math.radians(lon1)
    lat2 = math.radians(lat2)
    lon2 = math.radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    distance = R * c
    return distance

"""_TODO:_ After obtained its coordinate, create a `folium.Marker` to show the distance

"""

import folium
from folium import Marker # Corrección en la importación
from folium.features import DivIcon

# Supongamos que ya tienes 'site_map' creado

# Supongamos que tienes un diccionario con las coordenadas de la costa más cercana para cada sitio
coastline_coordinates = {
    'CCAFS LC-40': {'lat': 28.56367, 'lon': -80.57163},
    'KSC LC-39A': {'lat': 28.572, 'lon': -80.655}, # Reemplaza con tus coordenadas reales
    'VAFB SLC-4E': {'lat': 34.632, 'lon': -120.626}, # Reemplaza con tus coordenadas reales
    # Añade otros sitios si los tienes
}

# Supongamos que tienes las coordenadas de los sitios de lanzamiento en un diccionario o puedes accederlas desde spacex_df
launch_site_coordinates = {
    'CCAFS LC-40': (28.563197, -80.576820),
    'KSC LC-39A': (28.573255, -80.646895),
    'VAFB SLC-4E': (34.632834, -120.610746),
    # Añade otros sitios si los tienes
}

# Función para calcular la distancia (la misma que antes)
import math
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6371
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    distance = R * c
    return distance

# Iterar sobre los sitios de lanzamiento
for launch_site, coords in launch_site_coordinates.items():
    if launch_site in coastline_coordinates:
        coast_lat = coastline_coordinates[launch_site]['lat']
        coast_lon = coastline_coordinates[launch_site]['lon']
        distance = calculate_distance(coords[0], coords[1], coast_lat, coast_lon)

        # Crear un marcador en la ubicación de la costa con la distancia
        distance_marker = Marker(
            location=[coast_lat, coast_lon],
            icon=DivIcon(
                icon_size=(20, 20),
                icon_anchor=(0, 0),
                html=f'<div style="font-size: 12; color:#d35400;"><b>{distance:10.2f} KM</b></div>'
            )
        )
        distance_marker.add_to(site_map)

# Mostrar el mapa
site_map

"""_TODO:_ Draw a `PolyLine` between a launch site to the selected coastline point

"""

import folium
from folium import PolyLine # Importación correcta de PolyLine

# Supongamos que ya tienes 'site_map' creado

# Coordenadas del sitio de lanzamiento (ejemplo)
launch_site_lat = 28.563197
launch_site_lon = -80.576820

# Coordenadas de la costa más cercana (¡REEMPLAZA ESTO con tus coordenadas reales!)
coastline_lat = 28.56367
coastline_lon = -80.57163

# Crear la PolyLine
lines = PolyLine(locations=[(launch_site_lat, launch_site_lon), (coastline_lat, coastline_lon)], weight=1)

# Añadir la PolyLine al mapa
lines.add_to(site_map)

# Mostrar el mapa
site_map

"""Your updated map with distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

_TODO:_ Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>
"""

import folium
from folium import Marker, DivIcon, PolyLine

def add_proximity_marker(site_map, launch_site_lat, launch_site_lon, proximity_lat, proximity_lon, label, color):
    """
    Añade un marcador en la ubicación de proximidad y dibuja una línea hasta el sitio de lanzamiento.

    Args:
        site_map (folium.Map): El mapa de Folium al que se añadirán los elementos.
        launch_site_lat (float): Latitud del sitio de lanzamiento.
        launch_site_lon (float): Longitud del sitio de lanzamiento.
        proximity_lat (float): Latitud del punto de proximidad.
        proximity_lon (float): Longitud del punto de proximidad.
        label (str): Etiqueta para el marcador (e.g., "Ciudad Cercana", "Ferrocarril").
        color (str): Color del marcador y la línea.
    """

    # Crear el marcador en la ubicación de proximidad
    proximity_marker = Marker(
        location=[proximity_lat, proximity_lon],
        icon=DivIcon(
            icon_size=(20, 20),
            icon_anchor=(0, 0),
            html=f'<div style="font-size: 12; color:{color};"><b>{label}</b></div>'
        ),
        tooltip=label
    )
    proximity_marker.add_to(site_map)

    # Dibujar la línea desde el sitio de lanzamiento hasta la proximidad
    lines = PolyLine(
        locations=[(launch_site_lat, launch_site_lon), (proximity_lat, proximity_lon)],
        weight=2,
        color=color
    )
    lines.add_to(site_map)

# Ejemplo de coordenadas de sitios de lanzamiento (¡REEMPLAZA CON TUS COORDENADAS REALES!)
launch_site_coordinates = {
    'CCAFS LC-40': (28.563197, -80.576820),
    'KSC LC-39A': (28.573255, -80.646895),
    'VAFB SLC-4E': (34.632834, -120.610746),
}

# Ejemplo de coordenadas de puntos de interés cercanos (¡REEMPLAZA CON TUS COORDENADAS REALES!)
proximity_points = {
    'CCAFS LC-40': [
        {'lat': 28.573, 'lon': -80.58, 'label': 'Ciudad Cercana', 'color': 'blue'},
        {'lat': 28.56, 'lon': -80.56, 'label': 'Ferrocarril', 'color': 'green'},
        {'lat': 28.55, 'lon': -80.59, 'label': 'Carretera', 'color': 'red'}
    ],
    'KSC LC-39A': [
         {'lat': 28.58, 'lon': -80.66, 'label': 'Ciudad Cercana', 'color': 'blue'}, # Reemplaza con tus coordenadas reales
        {'lat': 28.57, 'lon': -80.63, 'label': 'Ferrocarril', 'color': 'green'},  # Reemplaza con tus coordenadas reales
        {'lat': 28.59, 'lon': -80.65, 'label': 'Carretera', 'color': 'red'}   # Reemplaza con tus coordenadas reales
    ],
    'VAFB SLC-4E': [
        {'lat': 34.64, 'lon': -120.62, 'label': 'Ciudad Cercana', 'color': 'blue'}, # Reemplaza con tus coordenadas reales
        {'lat': 34.62, 'lon': -120.60, 'label': 'Ferrocarril', 'color': 'green'},  # Reemplaza con tus coordenadas reales
        {'lat': 34.63, 'lon': -120.63, 'label': 'Carretera', 'color': 'red'}   # Reemplaza con tus coordenadas reales
    ],
}

# Iterar sobre los sitios de lanzamiento y añadir los marcadores de proximidad
for launch_site, coords in launch_site_coordinates.items():
    if launch_site in proximity_points:
        for point in proximity_points[launch_site]:
            add_proximity_marker(
                site_map,
                coords[0],
                coords[1],
                point['lat'],
                point['lon'],
                point['label'],
                point['color']
            )

# Mostrar el mapa
site_map



"""After you plot distance lines to the proximities, you can answer the following questions easily:
- Are launch sites in close proximity to railways?
- Are launch sites in close proximity to highways?
- Are launch sites in close proximity to coastline?
- Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Yan Luo](https://www.linkedin.com/in/yan-luo-96288783/)

### Other Contributors

Joseph Santarcangelo

## Change Log

|Date (YYYY-MM-DD)|Version|Changed By|Change Description|
|-|-|-|-|
|2021-05-26|1.0|Yan|Created the initial version|

Copyright © 2021 IBM Corporation. All rights reserved.
"""